CREATE TABLE IF NOT EXISTS PEOPLE (
    ID VARCHAR(36),
    NICKNAME VARCHAR(32) CONSTRAINT ID_PK PRIMARY KEY,
    NOME VARCHAR(100),
    BIRTHDATE CHAR(10),
    STACK VARCHAR(1024),
    BUSCA_TRGM TEXT GENERATED ALWAYS AS (
        LOWER(NOME || NICKNAME || STACK)
    ) STORED
);

CREATE EXTENSION PG_TRGM;
CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_PESSOAS_BUSCA_TGRM ON PEOPLE USING GIST (BUSCA_TRGM GIST_TRGM_OPS(SIGLEN=64));